### ISSUE TITLE
Skip Connection

### ISSUE THREAD

**Issue by gcouairon** [lizhuoq/WeatherLearn#1]
Hi, first of all, thank you, this is super useful.
I was wondering about the skip connection between layer 1 and layer 4 of Pangu Weather model.
In your implementation the skip is added after layer4, just before patch recovery, following original Pangu pseudo-code https://github.com/198808xc/Pangu-Weather/blob/403b7b69ee66f220f78afeeafa117dd0f52c0b7d/pseudocode.py#L236

However, this does not match the figure of PanguWeather (seems to indicate that skip is before layer4), and intuitively adding the skip right before patch recovery is way too late to do any meaningful processing of the skip connection. I think it might be an error in their pseudo-code.

Thoughts ?

**Comment by lizhuoq** [comment]
Thank you for bringing up this issue. I agree with your point. I've checked the arXiv original papers, and indeed, there is a mention of concatenating the output of the second layer of the encoder with the output of the seventh layer of the decoder. This doesn't align with their pseudocode. In this case, it seems like the eighth layer of the decoder would serve no purpose. I'm not sure if my understanding is correct.
![屏幕截图 2023-12-04 183940](https://github.com/lizhuoq/WeatherLearn/assets/100779955/ad555507-4479-4af4-82c0-2c76c09f9b8a)

**Comment by lizhuoq** [comment]
@gcouairon 
The correct approach follows the pseudocode implementation in the official repository. I have already asked the authors, and it turns out there was a typo in the paper, as detailed in the following [issue](https://github.com/198808xc/Pangu-Weather/issues/49#issuecomment-1848899191).
