### ISSUE TITLE
About the launch of FuXi.

### ISSUE THREAD

**Issue by dsuhoi** [lizhuoq/WeatherLearn#2]
Hello!
I have a number of questions about launching FuXi:
1. How much is estimated it may take to launch the model (32GB of CUDA was not enough for me to test run the model from [your examples](https://github.com/lizhuoq/WeatherLearn?tab=readme-ov-file#example-1) (There may be a memory leak?))?
2. The original model has an input parameter encoding the time shift ("temb" from "[time_encoding](https://github.com/tpys/FuXi/blob/main/fuxi.py#L21)"). Is there any way to combine the [weights of the model](https://github.com/tpys/FuXi) and retrain this network from Pytorch ?

P.S. My task is fine-tuning the model on a one-hour time grid.

**Comment by lizhuoq** [comment]
@dsuhoi Thank you for your issue, and I apologize for not responding promptly. I've been busy with other projects lately.

1. Regarding your first question, I haven't trained the FuXi model myself, but according to the FuXi arXiv paper, they used 8 NVIDIA A100 GPUs with a batch size of 1 per GPU. The A100 GPUs come in two memory configurations, 40GB and 80GB, and they didn't specify which memory configuration they used. Therefore, I would assume that if you're using a single GPU with a batch size set to 1, you would need at least 40GB of memory.
<img width="869" alt="fuxi" src="https://github.com/lizhuoq/WeatherLearn/assets/100779955/c99ca13e-3c2d-4684-bc8f-950b92b43173">

2. As for the second question about encoding time, they didn't mention this detail in the paper, but I speculate that a possible approach could be to perform element-wise addition or multiplication of the time encoding with the input matrix or hidden representation, similar to what was done in [MetNet3](https://arxiv.org/abs/2306.06079). Alternatively, you could use [Netron](https://netron.app/) to visualize their provided ONNX file and trace the "temb" tensor to see what computations are being performed.   
<img width="891" alt="metnet3" src="https://github.com/lizhuoq/WeatherLearn/assets/100779955/734f9d17-9ecd-4080-b79d-19b0b18b2f4c">

3. Lastly, regarding whether PyTorch supports fine-tuning ONNX files, I haven't tried it myself, and it's unlikely to be supported by PyTorch officially. You could try a third-party library like [onnx2torch](https://github.com/ENOT-AutoDL/onnx2torch), but I can't confirm its compatibility.

**Comment by dsuhoi** [comment]
Thanks for the good comments!  I found a solution to my problem in onnx2torch - I configured the conversion to the Pytorch model with minor corrections to the LayerNorm and Clip methods.
