### ISSUE TITLE
Dimensions mismatch when doing a forward pass in Fuxi()

### ISSUE THREAD

**Issue by visriv** [lizhuoq/WeatherLearn#3]
Hi,
I am trying to test FuXi() model on a weather dataset. However, I am facing an error when running it through the SwinTransformerV2Block(). The details are:

The input dimension is (B, in_chans = 1, T = 2, 46, 90)
patch_size=(2, 4, 4)
window_size = 8

While passing through the UTransformer block -> self.layer(x) -> SwinTransformerV2Block.forward() -> window_partition function, I am facing a dimension mismatch at [this line.](https://github.com/huggingface/pytorch-image-models/blob/3df4ffe914f7969344fc728c0b8a9b8289b3baa9/timm/models/swin_transformer_v2.py#L46C1-L47C1).

Would you please help? It looks like there is an issue with the padding function, or the window_size is not compatible.

My code:
```
B = 1  
in_chans = 1
out_chans = 1  # number of input channels or output channels
input = torch.randn(B, in_chans, 2, 46, 90)  # B C T Lat Lon
model = fuxi.Fuxi(img_size=(2, 46, 90), 
                patch_size=(2, 4, 4), 
                in_chans=in_chans, out_chans=out_chans,
                embed_dim=128, 
                num_groups=32, 
                num_heads=4, 
                window_size=8)  

output = model(input)  # B C Lat Lon


```

Error:

```
46 x = x.view(B, H // window_size[0], window_size[0], W // window_size[1], window_size[1], C)
47 windows = x.permute(0, 1, 3, 2, 4, 5).contiguous().view(-1, window_size[0], window_size[1], C)
48 return windows

RuntimeError: shape '[1, 1, 8, 2, 8, 128]' is invalid for input of size 18432
```

Your support would be very helpful.

**Comment by lizhuoq** [comment]
Thank you for your issue. I've been busy with other projects recently, but I'll look into your issue and aim to resolve it within 24 hours. I'll get back to you with an update once it's resolved.

**Comment by lizhuoq** [comment]
@visriv Thank you for reporting the issue. I have fixed the bug, which was caused by the `DownBlock` class in [fuxi.py](https://github.com/lizhuoq/WeatherLearn/blob/master/weatherlearn/models/fuxi/fuxi.py). You can find the specific changes in my latest commit. Additionally, I have added new unit tests in [tests/models/fuxi/test_down_block.py](https://github.com/lizhuoq/WeatherLearn/blob/master/tests/models/fuxi/test_down_block.py), and I have verified that everything is working correctly now.

**Comment by lizhuoq** [comment]
@visriv 
```
import torch
from weatherlearn.models import Fuxi


if __name__ == "__main__":
    B = 1  
    in_chans = 1
    out_chans = 1  # number of input channels or output channels
    input = torch.randn(B, in_chans, 2, 46, 90)  # B C T Lat Lon
    model = Fuxi(img_size=(2, 46, 90), 
                    patch_size=(2, 4, 4), 
                    in_chans=in_chans, out_chans=out_chans,
                    embed_dim=128, 
                    num_groups=32, 
                    num_heads=4, 
                    window_size=8)  

    output = model(input)  # B C Lat Lon
    print(output.shape)

```  
```
torch.Size([1, 1, 46, 90])
```

**Comment by visriv** [comment]
Thank you very much @lizhuoq . This is super helpful.
