### ISSUE TITLE
Typo in window shift?

### ISSUE THREAD

**Issue by hlinander** [lizhuoq/WeatherLearn#4]
https://github.com/lizhuoq/WeatherLearn/blob/18adc4f4a9587b4b7936b2c36668033212776b26/weatherlearn/models/pangu/pangu.py#L275

Shouldn't this rather be
`shifted_x = torch.roll(x, shifts=(-shift_pl, -shift_lat, -shift_lon), dims=(1, 2, 3))`

the un-shifting does implement asymmetric shifting correctly it seems like.

**Comment by lizhuoq** [comment]
@hlinander Thank you for bringing up the issue. I believe it might have been an error. I have corrected it now. Thank you for your correction.
