### ISSUE TITLE
Finetuning Existing Model Rather than training completely new Pangu

### ISSUE THREAD

**Issue by Declan-Curran1** [lizhuoq/WeatherLearn#5]
Hi Lizhuoq, thanks for this code - it has been really helpful. The Panguweather portion of this code is an accurate implementation of the official Panguweather repository in Pytorch. That is to say, it takes the full Pangu 24 hr .onnx model and runs a prediction + the code to train a pangu_lite & run this locally.

I'm looking to change the format of Panguweather slightly for downscaling and wanted to get your thoughts on taking the full .onnx model and finetuning the first few layers of this rather than training a completely new model. In examples\pangu-lite\train.py, how would I amend this to take up where the full Pangu .onnx model left off?

Appreciate any suggestions

**Comment by lizhuoq** [comment]
@Declan-Curran1 Thank you for your issue. If I understand correctly, you want to use the official open-source ONNX file from Pangu. You'd like to first import its weights into PyTorch format, then you want to either simplify the original Pangu model or modify its structure while retaining the pre-trained weights, and perform some minor fine-tuning, correct?

**Comment by lizhuoq** [comment]
@Declan-Curran1 Actually, PyTorch officially doesn't support importing from ONNX. However, you can try two open-source libraries, [onnx2pytorch](https://github.com/Talmaj/onnx2pytorch) and [onnx-pytorch](https://github.com/fumihwh/onnx-pytorch), which might be helpful. I'm sorry, but personally, I haven't tried importing ONNX into PyTorch. However, I'm interested in trying to solve this issue, but I've been busy with other projects lately, so I plan to allocate time next week to find a solution. If you come across a solution before then, please feel free to let me know. Please keep this issue open, and I'll get back to you within 7 days.

**Comment by lizhuoq** [comment]
@Declan-Curran1 You can also refer to this [issue](https://github.com/lizhuoq/WeatherLearn/issues/2#issuecomment-1950185214) where it seems someone found a solution using onnx2torch.

**Comment by Declan-Curran1** [comment]
Thanks for the prompt reply @lizhuoq, your summary is correct. Rather than train a new a completely new pangu model using the Pangu() function you have created in 'pangu.py', I'm trying to take the already existing .onnx model as a base and finetune based off this. I've tried importing the model into PyTorch using onnx2torch but having trouble actually working with it as a normal torch model and converting/accessing the underlying weights to further finetune. 

After using:

```import os
import numpy as np
import onnx
from onnx import numpy_helper
import onnxruntime as ort
from onnx2torch import convert

model_24 = onnx.load('pangu_weather_24.onnx')
tm = convert(model_24) #Convert onnx model to torch

for layer in tm.children():
    print(layer.state_dict())
```

I can access the weights from here but having trouble finetuning this as a normal torch model

**Comment by lizhuoq** [comment]
@Declan-Curran1 Sorry for replying to you so late. I've been busy with other projects recently. Please forgive me. You can refer to my latest submission [finetune](https://github.com/lizhuoq/WeatherLearn/tree/master/finetune). If you have any questions, feel free to contact me anytime.

**Comment by Declan-Curran1** [comment]
Thanks @lizhuoq. Really appreciate it
