### ISSUE TITLE
Pangu: Wong surface - upper air concatenation order?

### ISSUE THREAD

**Issue by mikael10j** [lizhuoq/WeatherLearn#7]
Hello,

It seems that there is a typo in the order of the concatenation between surface and upper air tokens in Pangu and Pangu lite. In pangu.py, line 427 (or 546):
`x = torch.concat([surface.unsqueeze(2), upper_air], dim=2)`
However, in the Pangu lite example, the upper air pressure levels are organized in ascending order, from 50 to 1000 because of `pLevels = sorted(list(upper_air_mean.keys()))` in `WeatherLearn/tree/master/examples/pangu_lite/data_utils.py`. 

So this way, attention is computed between surface and the highest atmospheric level, which is not desirable from a physical point of view.

Am I missing something?
Best,

**Comment by lizhuoq** [comment]
@mikael10j Thank you for your issue. Please refer to the [official pseudocode](https://github.com/198808xc/Pangu-Weather/blob/72bdd99096721e1a1f8912c37a9a3aff9ff0a4f2/pseudocode.py#L266-L267)
