### ISSUE TITLE
伏羲模型中最后一层的问题

### ISSUE THREAD

**Issue by morestart** [lizhuoq/WeatherLearn#8]
文章中使用了全连接，本仓库使用interpolate是为了降低计算量吗

**Comment by lizhuoq** [comment]
@morestart 我觉得整个模型的计算复杂度主要集中在attention部分，也就是vit的部分，我个人觉得最后一层dense或者interpolate对最终的结果影响不是很大。最后谢谢你的关注，这个仓库有特别多不完善的地方，但我今年忙于其他事情，明年我打算按照面向对象编程重构这个仓库，如果你还有任何问题，欢迎和我联系！

**Comment by IncubatorShokuhou** [comment]
> @morestart 我觉得整个模型的计算复杂度主要集中在attention部分，也就是vit的部分，我个人觉得最后一层dense或者interpolate对最终的结果影响不是很大。最后谢谢你的关注，这个仓库有特别多不完善的地方，但我今年忙于其他事情，明年我打算按照面向对象编程重构这个仓库，如果你还有任何问题，欢迎和我联系！

敲碗等重构。另外不知道风乌等其他模型的优先度是在重构前还是重构之后？

**Comment by lizhuoq** [comment]
@IncubatorShokuhou Hi，特别谢谢你的支持，我想的还是优先重构或者是重构和模型并行，现在的仓库存在特别多需要改进的地方，最早在11月份开始，然后会长期维护这个项目，可能会实现基于CNN, ViT, Diffusion等的模型，重构的框架参考[Time-Series-Library](https://github.com/thuml/Time-Series-Library)，但为了真正提升这个仓库的可用性，我打算利用ERA5来进行预训练，这很重要，因为只有训练过程看到loss curve后才能不断发现并完善代码的细节问题，但这也需要大量的时间debug。如果进展顺利的话，后期应该会加上lora的微调方式，如果你还有任何问题，欢迎和我联系！

**Comment by morestart** [comment]
如果是全连接的话 最后恢复到721x1440尺寸的话显存占用应该更高吧？

**Comment by morestart** [comment]
如果在推理阶段使用全连接的话是不是更平滑一些？

**Comment by lizhuoq** [comment]
> 如果在推理阶段使用全连接的话是不是更平滑一些？

理论上是的，可能对于psnr或者ssim这种指标会更好
